feature/PWA: installable , offline mode
carefortheliving/frontend pull request #62
Opened 2021-04-24 14:49 UTC by Sravan2305

PWA functionality

2021-04-24 14:54 UTC, MiKr13 requested changes
Please implement appropriate changes

2021-04-24 14:54 UTC, MiKr13 commented on public/ofline.html
> +<!DOCTYPE html>
Rename this file to offline.html please.

2021-04-24 14:54 UTC, MiKr13 commented on src/serviceWorker.ts
> +          //Service Worker Registration Succesful
Service worker registeration can be notified in console as it's more of a convention so please put
```js
console.log('Service Worker Registered');
```
Also handle .catch case for errors!

2021-04-25 05:33 UTC, alok722 commented
LGTM

2021-04-25 05:33 UTC, alok722 approved these changes
Look goods, merging

2021-04-25 05:34 UTC, merged